"""empty message

Revision ID: 3dc1cb2cea8e
Revises: 3e73ef45c3b8
Create Date: 2024-05-12 18:32:29.604507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dc1cb2cea8e'
down_revision = '3e73ef45c3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('post_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.drop_column('borad_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borad_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_2', 'board', ['borad_id'], ['id'])
        batch_op.drop_column('board_id')

    # ### end Alembic commands ###
